struct TPointD{double x;double y;};
struct TPointD_3D{double x;double y;double z;};
struct TPointDbool{double x;double y;bool b;};
struct TPointD_3Dbool{double x;double y;double z;bool b;};
struct TMinMax_d{double MaxX;double MaxY;double MinX;double MinY;};
struct TMinMedAvgMax_d{double Min;double Med;double Avg;double Max;};
struct TTextNumber{AnsiString text;double number1;int number2;};
struct TTextWNumber{UnicodeString text;double number1;int number2;};
struct TTextXYZ{AnsiString text;long X;long Y;long Z;};
struct TTextXYZd{AnsiString text;double X;double Y;double Z;};
struct T2Rect{TRect rect1; TRect rect2;};
struct T3Rect{TRect rect0; TRect rect1; TRect rect2;};
struct T4Rect{TRect rect0; TRect rect1; TRect rect2; TRect rect3;};
struct T5Rect{TRect rect0; TRect rect1; TRect rect2; TRect rect3; TRect rect4;};
struct T8Rect{TRect rect0; TRect rect1; TRect rect2; TRect rect3; TRect rect4; TRect rect5; TRect rect6; TRect rect7; TRect rect8;};
